export const AUTH_SERVICE = "AUTH_SERVICE";
export const USERS_SERVICE = "USERS_SERVICE";
export const EXTINGUISHERS_SERVICE = "EXTINGUISHERS_SERVICE";
export const REPORTS_SERVICE = "REPORTS_SERVICE";
export const INSPECTIONS_SERVICE = "INSPECTIONS_SERVICE";
