import {
  Body,
  Controller,
  Delete,
  Get,
  Inject,
  Param,
  Post,
  UseGuards,
} from "@nestjs/common";
import type { ClientProxy } from "@nestjs/microservices";
import {
  ApiBearerAuth,
  ApiBody,
  ApiForbiddenResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiTags,
} from "@nestjs/swagger";

import { OkResponseDto } from "@shared/common/dto/ok-response.dto";

import { FIRE_PATTERNS } from "@shared/microservices/patterns";
import { Role } from "@shared/common/enums/role.enum";
import type { AuthenticatedUser } from "@shared/types/authenticated-user.type";
import { FIRE_SERVICE } from "../clients/microservices.constants";
import { MicroserviceProxyService } from "../clients/microservice-proxy.service";
import { JwtAuthGuard } from "../auth/guards/jwt-auth.guard";
import { RolesGuard } from "../auth/guards/roles.guard";
import { Roles } from "../auth/decorators/roles.decorator";
import { CurrentUser } from "../auth/decorators/current-user.decorator";
import { GenerateReportDto } from "./dto/generate-report.dto";

@ApiTags("reports")
@Controller("reports")
export class ReportsGatewayController {
  constructor(
    @Inject(FIRE_SERVICE) private readonly fireClient: ClientProxy,
    @Inject(MicroserviceProxyService) private readonly proxy: MicroserviceProxyService,
  ) {}

  @ApiOperation({ summary: "Generate a real-time report snapshot" })
  @ApiBearerAuth()
  @ApiBody({ type: GenerateReportDto })
  @UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(Role.admin, Role.inspector, Role.user)
  @Post()
  generate(@CurrentUser() user: AuthenticatedUser, @Body() dto: GenerateReportDto) {
    return this.proxy.send(this.fireClient, FIRE_PATTERNS.REPORT_GENERATE, {
      generatedById: user.sub,
      dto,
    });
  }

  @ApiOperation({ summary: "List reports generated by current user" })
  @ApiBearerAuth()
  @UseGuards(JwtAuthGuard)
  @Get()
  list(@CurrentUser() user: AuthenticatedUser) {
    return this.proxy.send(this.fireClient, FIRE_PATTERNS.REPORT_LIST, {
      generatedById: user.sub,
    });
  }

  @ApiOperation({ summary: "View report with data snapshot" })
  @ApiBearerAuth()
  @ApiParam({ name: "id" })
  @UseGuards(JwtAuthGuard)
  @Get(":id")
  view(@CurrentUser() user: AuthenticatedUser, @Param("id") id: string) {
    return this.proxy.send(this.fireClient, FIRE_PATTERNS.REPORT_VIEW, {
      id,
      userId: user.sub,
      isAdmin: user.role === Role.admin,
    });
  }

  @ApiOperation({ summary: "Delete a report" })
  @ApiBearerAuth()
  @ApiParam({ name: "id" })
  @ApiOkResponse({ type: OkResponseDto })
  @ApiForbiddenResponse({ description: "Can only delete own reports unless admin" })
  @UseGuards(JwtAuthGuard)
  @Delete(":id")
  remove(@CurrentUser() user: AuthenticatedUser, @Param("id") id: string) {
    return this.proxy.send(this.fireClient, FIRE_PATTERNS.REPORT_REMOVE, {
      id,
      userId: user.sub,
      isAdmin: user.role === Role.admin,
    });
  }
}
