export const AUTH_PATTERNS = {
  REGISTER: "auth.register",
  LOGIN: "auth.login",
  LOGOUT: "auth.logout",
  VERIFY_EMAIL: "auth.verify_email",
  RESEND_VERIFICATION: "auth.resend_verification",
  CHANGE_PASSWORD: "auth.change_password",
  REQUEST_PASSWORD_RESET: "auth.request_password_reset",
  VERIFY_PASSWORD_RESET_OTP: "auth.verify_password_reset_otp",
  RESET_PASSWORD: "auth.reset_password",
  RESEND_PASSWORD_RESET: "auth.resend_password_reset",
} as const;

export const NOTIFICATIONS_PATTERNS = {
  LIST: "notifications.list",
  MARK_READ: "notifications.mark_read",
  MARK_UNREAD: "notifications.mark_unread",
} as const;

export const USERS_PATTERNS = {
  ME: "users.me",
  UPDATE_ME: "users.update_me",
  CHANGE_PASSWORD: "users.change_password",
  FIND_ALL: "users.find_all",
  FIND_ONE: "users.find_one",
  CREATE: "users.create",
  UPDATE: "users.update",
  DELETE: "users.delete",
  UPLOAD_AVATAR: "users.upload_avatar",
  REMOVE_AVATAR: "users.remove_avatar",
} as const;

export const FIRE_PATTERNS = {
  EXTINGUISHER_REGISTER: "fire.extinguisher.register",
  EXTINGUISHER_LIST: "fire.extinguisher.list",
  EXTINGUISHER_VIEW: "fire.extinguisher.view",
  EXTINGUISHER_UPDATE: "fire.extinguisher.update",
  EXTINGUISHER_REMOVE: "fire.extinguisher.remove",
  EXTINGUISHER_ASSIGN: "fire.extinguisher.assign",
  EXTINGUISHER_UNASSIGN: "fire.extinguisher.unassign",
  EXTINGUISHER_MY_LIST: "fire.extinguisher.my_list",
  INSPECTION_SCHEDULE: "fire.inspection.schedule",
  INSPECTION_LIST: "fire.inspection.list",
  INSPECTION_VIEW: "fire.inspection.view",
  INSPECTION_COMPLETE: "fire.inspection.complete",
  INSPECTION_UPDATE: "fire.inspection.update",
  INSPECTION_REMOVE: "fire.inspection.remove",
  MAINTENANCE_LOG: "fire.maintenance.log",
  MAINTENANCE_LIST: "fire.maintenance.list",
  MAINTENANCE_VIEW: "fire.maintenance.view",
  MAINTENANCE_UPDATE: "fire.maintenance.update",
  MAINTENANCE_REMOVE: "fire.maintenance.remove",
  COMPLIANCE_CHECK: "fire.compliance.check",
  COMPLIANCE_LIST: "fire.compliance.list",
  COMPLIANCE_VIEW: "fire.compliance.view",
  COMPLIANCE_SUMMARY: "fire.compliance.summary",
  COMPLIANCE_REMOVE: "fire.compliance.remove",
  REPORT_GENERATE: "fire.report.generate",
  REPORT_LIST: "fire.report.list",
  REPORT_VIEW: "fire.report.view",
  REPORT_REMOVE: "fire.report.remove",
  SITE_CREATE: "fire.site.create",
  SITE_LIST: "fire.site.list",
  SITE_VIEW: "fire.site.view",
  SITE_UPDATE: "fire.site.update",
  SITE_REMOVE: "fire.site.remove",
  REQUEST_CREATE: "fire.request.create",
  REQUEST_LIST: "fire.request.list",
  REQUEST_MY_LIST: "fire.request.my_list",
  REQUEST_VIEW: "fire.request.view",
  REQUEST_APPROVE: "fire.request.approve",
  REQUEST_REJECT: "fire.request.reject",
  REQUEST_CANCEL: "fire.request.cancel",
} as const;

export const REPORTING_PATTERNS = {
  STOCK_SUMMARY: "reporting.stock.summary",
  STOCK_TREND: "reporting.stock.trend",
  INSPECTION_STATUS: "reporting.inspection.status",
  EXPIRED_EXTINGUISHERS: "reporting.expired",
  MAINTENANCE_HISTORY: "reporting.maintenance.history",
} as const;
